### ISSUE TITLE
Just a FYI

### ISSUE THREAD

**Issue by collizo4sky** [scottopolis/edd-metrics#1]
@scottopolis (This](https://github.com/scottopolis/edd-metrics/blob/master/edd-metrics.php#L230) isn't 100 percent true as you can replace 'EDD_Metrics_activation' function with an array with the first value set to the class instance and the second the class method to call. 

Read my post on WordPress hook system https://www.sitepoint.com/understanding-namespaces-wordpress-hook-system/

Btw nice work with this plugin. Love the graph and i just might copy the design of how stats are display in my next project 😄

**Comment by scottopolis** [comment]
Hmm, this is boilerplate code from Pippin, I'll have to ping him on this one.

Thanks!

**Comment by collizo4sky** [comment]
Just thought I should let you know. We all learn everyday.
