### ISSUE TITLE
Escaped HTML in dashboard

### ISSUE THREAD

**Issue by pippinsplugins** [scottopolis/edd-metrics#10]
![screen shot 2016-09-06 at 2 24 30 pm](https://cloud.githubusercontent.com/assets/1034109/18287680/b4ba883c-743d-11e6-93ef-86b259636fbf.png)

**Comment by scottopolis** [comment]
Fixed in https://github.com/scottopolis/edd-metrics/commit/aa4a307d4f5889b4b484f75d37f8ce98fa7bdd44
