### ISSUE TITLE
JS errors on Today view

### ISSUE THREAD

**Issue by pippinsplugins** [scottopolis/edd-metrics#11]
When I select `Today` I get a bunch of JS errors.
![screen shot 2016-09-06 at 2 26 09 pm](https://cloud.githubusercontent.com/assets/1034109/18287733/ee5900a0-743d-11e6-946e-424462240db5.png)

**Comment by scottopolis** [comment]
So it turns out this plugin really doesn't work well for just a single day, so I'm just removing this option for now. Will look back into this later.
