### ISSUE TITLE
Revenue detail graph blank

### ISSUE THREAD

**Issue by leewillis77** [scottopolis/edd-metrics#15]
The mini graph on the main metrics page shows some activity:
https://www.dropbox.com/s/4coi0k113lzqt6o/Screenshot%202016-09-14%2012.33.44.png?dl=0

However - clicking through to the Revenue detail just gives a flat, 0 value graph:
https://www.dropbox.com/s/o8jv6yto3hxxuy9/Screenshot%202016-09-14%2012.33.26.png?dl=0

**Comment by scottopolis** [comment]
The revenue detail icon is a static image, not a representation of values. Are there any sales in the time period you chose for the revenue detail?

**Comment by leewillis77** [comment]
Hmm, strange - I just reactivated the plugin and the graph looks sensible now. I'll close in absence of being able to reproduce. Thanks for following up!
