### ISSUE TITLE
Earnings by Gateway report shows invalid payment gateway

### ISSUE THREAD

**Issue by leewillis77** [scottopolis/edd-metrics#16]
The earnings by gateway report lists "Amazon" in the key - however I've never (knowingly!) used Amazon payment gateway:

https://www.dropbox.com/s/zeuyvr9j8cany9s/Screenshot%202016-09-14%2012.35.30.png?dl=0

**Comment by scottopolis** [comment]
Hmm, ya it looks like all gateways show up as labels even if you aren't using them. I'll see if I can fix that, thanks for the report.

**Comment by scottopolis** [comment]
Fixed in 7a499d95338ac9d58c40751bf4b8301bbbe95036
