### ISSUE TITLE
Earnings by download pie chart only shows two products

### ISSUE THREAD

**Issue by leewillis77** [scottopolis/edd-metrics#17]
The key for the pie chart lists the products that I expect to be included, but the pie chart itself only has data for two products.

https://www.dropbox.com/s/nuuie6iv7tfkm6i/Screenshot%202016-09-14%2012.37.40.png?dl=0

**Comment by scottopolis** [comment]
The pie chart will only show products that have sales, are there sales for other products listed in the time period you selected?

**Comment by leewillis77** [comment]
Yes - there's a good mix...

**Comment by scottopolis** [comment]
The master branch has some console log outputs, can you install that and copy the logs here? https://github.com/scottopolis/edd-metrics
