### ISSUE TITLE
Uncaught TypeError: Cannot read property 'count' of null

### ISSUE THREAD

**Issue by pippinsplugins** [scottopolis/edd-metrics#2]
When loading the Metrics dashboard, I'm seeing this JS error:
```
Uncaught TypeError: Cannot read property 'count' of null
https://edd.com/basic/wp-content/plugins/edd-metrics/assets/js/admin.js?ver=1.0 line 86
```
I think it's because the refunds and renewals graphs have no data.

**Comment by scottopolis** [comment]
Thanks, fixed in https://github.com/scottopolis/edd-metrics/commit/0a5164e95068eaa87c2f4932994f955360583967
