### ISSUE TITLE
Decode HTML entities in chart labels

### ISSUE THREAD

**Issue by zackkatz** [scottopolis/edd-metrics#21]
My Downloads have HTML entities that should be decoded:

![Needs decoding](http://share.gravityview.co/G7kZ/y9nfjVYP+)

**Comment by pderksen** [comment]
Got the same thing here.

**Comment by scottopolis** [comment]
Thanks for the report, fixed in 19441ebb564b00b68a7ee8ff19d8a17b78b57099
