### ISSUE TITLE
Parse error on plugin activation

### ISSUE THREAD

**Issue by hishaman** [scottopolis/edd-metrics#26]
Parse error: syntax error, unexpected ‘[‘ in wp-content/plugins/edd-metrics/includes/class-edd-metrics-functions.php on line 302

**Comment by scottopolis** [comment]
Thanks for the bug report, I'm pretty sure it has to do with the ['num_days'] array key, but I can't replicate the error.

**Comment by scottopolis** [comment]
Gonna close this since I haven't had any other reports, feel free to reopen if you have any other information.
