### ISSUE TITLE
Incorrect parameter passed to get_earnings()

### ISSUE THREAD

**Issue by pippinsplugins** [scottopolis/edd-metrics#3]
In several places, the `get_earnings()` method of `EDD_Payment_Stats` is called like this:
```php
$earnings[] = $EDD_Stats->get_earnings( 0, $dt->format( "jS F, Y" ), false, array( 'publish', 'revoked' ) );
```
This method does not accept a status, so `array( 'publish', 'revoked' )` is incorrect.

Method definition:
```php
public function get_earnings( $download_id = 0, $start_date = false, $end_date = false, $include_taxes = true )
```

**Comment by scottopolis** [comment]
Thanks, fixed https://github.com/scottopolis/edd-metrics/commit/dc20283830e7be68b0d28a0dfca9e96254386350
