### ISSUE TITLE
Obey currency settings

### ISSUE THREAD

**Issue by wolffe** [scottopolis/edd-metrics#33]
The "Recent Activity" box currency seems to show US Dollars ($) when I have EUR in EDD Settings. The EDD widget on the Dashboard, also shows EUR, correctly.

See attached screenshot.

![caa944cd4fd1a468f909b2b07093b8a6](https://cloud.githubusercontent.com/assets/910240/19032042/8ff1f194-894f-11e6-8edf-8450081fe297.png)

**Comment by Netzberufler** [comment]
Thanks for the report. Fixed with #34
