### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by wolffe** [scottopolis/edd-metrics#35]
I don't have any refunds or discounted sales so far, and the boxes load forever:

![726e72132ee258c717ea07dd0eaec67d](https://cloud.githubusercontent.com/assets/910240/19035793/adf1f590-8963-11e6-97bc-99b2a6c8aefc.png)

Inspector's console shows:

`VM314:1 Uncaught SyntaxError: Unexpected end of JSON input`

I traced this in the minified .js file here:

`b.batch2response=function(f){var h=JSON.parse(f);`

I don't know what the intended behaviour should be, but never loading issue doesn't seem to be the correct approach. Maybe a "No data yet" message or something similar.

**Comment by scottopolis** [comment]
The loading is just an image, it isn't actually loading a request for that long. There shouldn't be an error though, let me see what I can find.

**Comment by wolffe** [comment]
I know it's just an image, but it should disappear or be replaced by a blank image. Looks good, anyway, thank you.
