### ISSUE TITLE
Unpaid Commissions Issue

### ISSUE THREAD

**Issue by davidsherlock** [scottopolis/edd-metrics#37]
Hi Scott,

There seems to be an issue with the "Unpaid commissions" reporting. For some reason it's reporting "undefinied12.00". I am using GBP as my preferred currency.

It's showing correctly as 1 unpaid commission, but the amount value has "undefined" prefixed for the total value.

It would also be useful to have taxes reported within the metrics (ideally by monthly, yearly, etc.).

Great plugin none the less!

Thanks,
David

**Comment by scottopolis** [comment]
Hmm, I don't have this plugin to test, I'll have to get a copy.  @growdev do you have an idea what this could be?

**Comment by growdev** [comment]
Hmm, I'm seeing it too.  I'll research and provide a fix.
