### ISSUE TITLE
Use count() in get_customers() and compare_customers()

### ISSUE THREAD

**Issue by pippinsplugins** [scottopolis/edd-metrics#4]
The EDD customers DB class provides a `count()` method that will make your `get_customers()` and `compare_customers()` methods much more efficient.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-db-customers.php#L523

**Comment by scottopolis** [comment]
Thanks for the tip, updated in https://github.com/scottopolis/edd-metrics/commit/dc20283830e7be68b0d28a0dfca9e96254386350
