### ISSUE TITLE
Previous-year revenue numbers are all zero

### ISSUE THREAD

**Issue by scottbuscemi** [scottopolis/edd-metrics#44]
Now that it's 2017, daily revenue numbers are showing as $0 for all of the 2016 dates. This is on the Revenue Detail page:

![screen shot 2017-01-07 at 1 17 21 pm](https://cloud.githubusercontent.com/assets/4336848/21745232/9bf9aebe-d4db-11e6-8a67-bdd888a55945.png)

**Comment by scottopolis** [comment]
That's not good, looking into it

**Comment by scottopolis** [comment]
Should be fixed with b23d14f815ac5e9eea762195487b2f75781ab578

You can download the latest master branch, or I'll push this to .org next week. Thanks for the bug report!

**Comment by scottopolis** [comment]
version 0.5.1 pushed to .org with this fix
