### ISSUE TITLE
Recurring Next One Year

### ISSUE THREAD

**Issue by jordymeow** [scottopolis/edd-metrics#46]
Hello,

I wonder if this plugin development is still active, but I really hope so, because it is awesome! Would it be easy to add "Recurring Next 1 Year" next to the already existing "Recurring Next 30 Days"? It's basically the only main statistics missing for me. It would be awesome to have it.

Cheers and all the best for 2018 :)

**Comment by scottopolis** [comment]
EDD actually has that stat already in the dashboard widget, under Estimated Recurring Revenue-
 Next 365 Days.

I probably won't add it to this plugin, thanks for the suggestion though.
