### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by gilbitron** [scottopolis/edd-metrics#7]
Just installed this on my established EDD site. See this error on all Metrics pages:

![google chrome - github com - - screen shot 6 sep 2016 5 09 24 pm](https://cloud.githubusercontent.com/assets/203882/18281404/ab3a39a8-7454-11e6-8e79-b7429182186e.png)

On the main page the Refunds/Discounts/Renewals/New Subscriptions panels never load. On the revenue page 6/12 months, today, this month renewal rate and both the earnings graphs don't load (revenue graph seems ok).

**Comment by scottopolis** [comment]
Hmm, this is really hard to diagnose without seeing the JSON.  If you have a staging or local site,  you add this to /includes/class-edd-metrics-functions.php line 157

var_dump($metrics);

If you post that output here I can take a look. 

<img width="438" alt="screen shot 2016-09-09 at 11 31 48 am" src="https://cloud.githubusercontent.com/assets/5324977/18398297/09d9a998-7681-11e6-8d8f-06fee1996965.png">

**Comment by scottopolis** [comment]
Actually my last comment won't work. I just pushed a commit that added some logs, can you replace your plugin with the master branch: https://github.com/scottopolis/edd-metrics/archive/master.zip

Open a browser inspector and show me the console logs, that should help me fix the issue.

Thanks!

**Comment by gilbitron** [comment]
Thanks Scott. I installed the master.zip and I see the logs in console however it seems to be working now. You must have already fixed the issue 😄
