### ISSUE TITLE
New quickselect options

### ISSUE THREAD

**Issue by flowdee** [scottopolis/edd-metrics#8]
- This year
- Last year

![bildschirmfoto 2016-09-06 um 19 12 21](https://cloud.githubusercontent.com/assets/2278756/18283505/dfe609f0-7465-11e6-9dc3-9b39efe8f032.png)

would be very handy 👍

**Comment by scottopolis** [comment]
Doing calculations for an entire year is beyond the scope of this plugin. For larger sites that could be millions of records, and it just can't handle that yet.

Hopefully at some point we can do that ;)

**Comment by flowdee** [comment]
makes sense but I'm able to select the year by date anyway, right?

**Comment by scottopolis** [comment]
Ya, it won't display the graph if you do more than 3 months, but it will try to do the metrics. It should work if you don't have a crazy number of sales.

**Comment by flowdee** [comment]
Yeah of course projects with tons of sales would have problems here but for "normal" project it's really interesting to compare year by year 👍
